# Power BI Build Pipeline

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Install the Power BI PowerShell module
      Install-Module -Name MicrosoftPowerBIMgmt

      # Connect to Power BI using Service Principal
      $clientId = '281b83c6-b759-489d-87cd-e2822aa80e6d'
      $clientSecret = 'jbL8Q~OXlG6CJjIdRV3qkLXT114tKIG0nsA0ibz3'
      $tenantId = '261b775f-255a-40b3-8b29-3bf762602e84'
      Connect-PowerBIServiceAccount -ClientId $clientId -ClientSecret $clientSecret -TenantId $tenantId

      # Deploy the report to the Power BI workspace
      $FilePath = "./PowerBI-CI-CD-using-AzureDevops/COVID-19 US Tracking Sample.pbix"
      $WorkspaceId = '48a697cb-60f6-4efc-b80c-c1f0eedf3cb1'
      #$GroupId = 'your-group-id'
      Import-PowerBIReport -Path $FilePath -WorkspaceId $WorkspaceId

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'artifact'
