trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
  - job: Build_Job
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourceDirectory)'
        Contents: '**/*.pbix'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container' 
- stage: Deploy
  jobs:
  - job: Deploy_Job
    steps:
    - task: AzurePowerBIServiceConnection@1
      inputs:
        azureSubscription: 'fcbaa624-ed53-476c-bf2f-76d1609690df'
        powerBIWorkspace: 'My-Space'
    - task: AzurePowerBIEmbed@1
      inputs:
        azureSubscription: 'fcbaa624-ed53-476c-bf2f-76d1609690df'
        powerBIWorkspace: 'My-Space'
        reportName: 'COVID-19 US Tracking Sample'
        datasetName: 'COVID-19 US Tracking Sample'
        action: 'Publish'