# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**.pbix'
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: |
        # Install the Power BI command-line interface (CLI)
        echo "Installing Power BI CLI..."
        npm install -g powerbi-cli
        pip install pytest pytest-azurepipelines
        pip install msal
        # Authenticate with Power BI using python script
        echo "Authenticating with Power BI using python script..."
        python powerbi1.py

- task: maikvandergaag.maikvandergaag-power-bi-actions.PowerBIActions.PowerBIActions@5
  displayName: 'Power BI Action: Publish'
  inputs:
    PowerBIServiceEndpoint: powerbi
    WorkspaceName: 'My-Space'
    PowerBIPath: '$(System.DefaultWorkingDirectory)'

