trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**.pbix'
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Authenticate using the Azure AD PowerShell module
      Install-Module -Name Az -AllowClobber -Scope CurrentUser
      Connect-AzAccount

      # Get the access token for Power BI REST API
      $accessToken = (Get-AzAccessToken -ResourceUrl "https://analysis.windows.net/powerbi/api").AccessToken

      # Set the headers for the REST API call
      $headers = @{
          "Content-Type" = "application/json"
          "Authorization" = "Bearer $accessToken"
      }

      # Set the import ID and the report name
      $importId = "your-import-id"
      $reportName = "COVID-19 US Tracking Sample"

      # Set the REST API endpoint URL
      $url = "https://api.powerbi.com/v1.0/myorg/imports/$importId/reports"

      # Publish the report
      Invoke-RestMethod -Uri $url -Method POST -Headers $headers
