# Power BI Deployment pipeline

name: Power BI Deployment

resources:
- repo: self

jobs:
- job: Build
  pool:
    vmImage: windows-latest
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Import the Power BI PowerShell module
        Import-Module -Name MicrosoftPowerBIMgmt
        # update $userName and $password with your user credentials
        $userName = "dhananjay@cloudaeon.net"
        $password = "LIfe@@787898"

        # convert password to secure string
        $securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force

        # create PSCredential object to serve as login credentials
        $credential = New-Object -TypeName System.Management.Automation.PSCredential `
        -ArgumentList $userName, $securePassword

        # log into Power BI unattended without any user interaction
        $user = Connect-PowerBIServiceAccount -Credential $credential
        $userName = $user.UserName 
        Write-Host
        Write-Host "Now logged in as $userName"
        # log into Power BI unattended without any user interaction
        $user = Connect-PowerBIServiceAccount -Credential $credential
        Get-PowerBIWorkspace | Format-Table Name, Id

        # Authenticate to Power BI
        Connect-PowerBI -Credential (Get-Credential)

        # Define the path to the Power BI report file (pbix)
        $pbixFilePath = '$(System.DefaultWorkingDirectory)/report.pbix'

        # Define the name of the workspace
        $workspace = 'My-Space'

        # Build the Power BI artifact
        $import = New-PowerBIReport -Path $pbixFilePath -Name 'Report'

        # Publish the artifact to the Power BI workspace
        Publish-PowerBIReport -Import $import -Workspace $workspace

        # Disconnect from Power BI
        Disconnect-PowerBI
